import Head from "next/head";

export default function Home() {
  return (
    <div className="app">
      <Head>
        <title>{`${'Name Page'} - AMELA Technology`}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
